name: WorldGuardSafeSuperPickaxe
main: safesuperpickaxe.WorldGuardSafeSuperPickaxe
version: 0.1.0
depend: [WorldGuard]
softdepend: [LogBlock]
author: sirknighting
commands:
  sspa:
    description: Controls usage of the safesuperpickaxe
    usage: /<command> [on|off]
    permission: sspa.use
    permission-message: Nope!
    aliases: [safesuperpickaxe,sspa]
permissions:
  sspa.use:
    default: op
    description: allows usage of the SafeSuperPickaxe